# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-08-13 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.TextField(blank=True, db_column='BUSINESS_NAME', null=True)),
                ('update_timestamp', models.DateTimeField(auto_now_add=True)),
                ('latest_in', models.BooleanField(db_column='LATEST_IN', default=True)),
            ],
            options={
                'db_table': 'BUSINESS',
                'managed': True,
            },
        ),
    ]
