# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-08 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sybmol', models.TextField(blank=True, db_column='SYYMBOL', null=True)),
                ('price', models.FloatField(blank=True, db_column='PRICE', null=True)),
                ('update_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TICKER',
                'managed': True,
            },
        ),
    ]
