# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-08 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='latest_in',
            field=models.BooleanField(db_column='LATEST_IN', default=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='sybmol',
            field=models.TextField(blank=True, db_column='SYMBOL', null=True),
        ),
    ]
