# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20160915_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='apartment',
            field=models.TextField(blank=True, db_column='APARTMENT', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.TextField(blank=True, db_column='CITY', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.TextField(blank=True, db_column='STATE', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.TextField(blank=True, db_column='STREET', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zip',
            field=models.BigIntegerField(blank=True, db_column='ZIP_CODE', null=True),
        ),
    ]
