# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20160915_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True},
        ),
    ]
