# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20160915_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
        migrations.RemoveField(
            model_name='company',
            name='street',
        ),
        migrations.RemoveField(
            model_name='company',
            name='zip',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, db_column='ADDRESS', null=True),
        ),
    ]
